--- 
version: "3.7"
services:
  front_end:
    image: josephigbi/petclinic-angular
    container_name: front_end
    build: ./spring-petclinic-angular 
    ports:
    - target: 4200
      published: 4200
      protocol: tcp
  back_end:
    image: springcommunity/spring-petclinic-rest
    container_name: back_end
    ports:
    - target: 9966
      published: 9966
      protocol: tcp
  nginx:
    image: josephigbi/petclinic-nginx
    container_name: nginx
    build: ./nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf







