---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 4200
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: 
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend 
        image: josephigbi/petclinic-angular
        ports:
        - containerPort: 4200
        env:
        - name: IP_address
          value: "{{IP_address}}"
